### ISSUE TITLE
Detect Network Settings Changes / VPN / DNS

### ISSUE THREAD

**Issue by TraderStf** [pirate/security-growler#24]
Hello!

Would it be possible to detect various changes to the network settings?
DNS, VPN,IP4/6...

Can use these 2, great ones:
http://ipv6-test.com
http://ip-api.com
http://whatismyipaddress.com/proxy-check

**Comment by JayBrown** [comment]
You don't need external websites. You can listen locally, regarding VPN e.g. for `configd: network changed` which also comes with "v4" or "v6" info. (It doesn't give you your actual public IP; for that you would need external IP services, and you would need to extend the .py script.) As for DNS, I think the system.log reads `mDNSResponder: SIGHUP: Purge cache`, when DNS changes. (But I'm not sure about the latter; at least that's what happens in my case: I use different DNS when on VPN.)

**Comment by pirate** [comment]
Great ideas, here's how I think they should be implemented:

 - new DNS change parser: `mDNSResponder: SIGHUP: Purge cache`
 - new VPN change parser: `configd: network changed`
 - new public IP change source: `dig +short myip.opendns.com @resolver1.opendns.com`
 - new local IP change source: `ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | xargs`

The IP change alerts will have to be implemented as sources, since they cant be parsed from the system log.  Sources have the ability to run a command on every call, e.g. `dig` or `ifconfig`.  I'll work on this when I have some spare time.

**Comment by JayBrown** [comment]
`dig +short myip.opendns.com @resolver1.opendns.com` is definitely the fastest IP lookup. (STUN is also fast, but not everyone has that.)

An alternate for the local IP, maybe slightly faster, could be
`ipconfig getifaddr $(route get 0.0.0.0 2>/dev/null | /usr/bin/awk '/interface: / {print $2}')`

**Comment by pirate** [comment]
My target is to get DNS and VPN settings out with `v2.3` next week, and local/pub ip changes after that (since it requires writing new loggers it takes a bit longer).

**Comment by TraderStf** [comment]
networksetup command has lot of info:
networksetup -listnetworkserviceorder
networksetup -listallnetworkservices
networksetup -getinfo xxx to get local ip4 and ip6, router...
networksetup -getdnsservers xxx to get DNS4-6 Resolvers

did not check, but ip6 is missing from your sample?

**Comment by JayBrown** [comment]
Some remarks:

- a command like `ipconfig getpacket en0` would just output the system/network state at a certain time. You would have to save this info in a prefs file or a db, then run the command again at regular intervals, and diff the results. I don't think this is what **Security Growler** does, nor what it should do. It's just a monitor/watcher, not a scanner. What you seem to be looking for is an IP or network scanner background script run by an agent or daemon.

- Regarding the VPN changes, monitoring system.log for `configd[]: network changed` will probably produce false positives, because I received such a log entry last night (see below), even though I didn't do anything VPN-wise. It was just the computer reconnecting after wake from sleep. So if the configd entries are something like this:
```
DATE LOCALHOST configd[]: network changed: v4(en1-:192.168.178.2) DNS- Proxy- SMB-
DATE LOCALHOST configd[]: network changed: DNS* Proxy
DATE LOCALHOST configd[]: network changed: v4(en1!:192.168.178.2) DNS+ Proxy+ SMB+
```
it could be anything, while something like this:
```
DATE LOCALHOST configd[62]: network changed: v4(en1:192.168.178.2, utun1+:10.10.30.15) DNS* Proxy SMB
DATE LOCALHOST configd[62]: network changed: v4(utun1/:10.10.30.15, en1\:192.168.178.2) DNS! Proxy- SMB-
DATE LOCALHOST configd[62]: network changed
```
is a clear sign of VPN. However, if we ignore the first set of log entries above, we would only know when a VPN connection is established, not when it is broken down or disconnected by the user. So we have to live with false positives, unless we find a more elegant way.

**Comment by TraderStf** [comment]
I don't all technical about VPN, but some are not "modifying'' values visible in Apple Network, VPN on or off. Is it Apple Network prefs which is not updated if not 'directly' changed?

**Comment by TraderStf** [comment]
An idea, groups like on this page, top 4 groups.
http://www.whatsmyip.org/port-scanner/

**Comment by pirate** [comment]
@JayBrown actually security growler does run commands periodically and diff subsequent outputs to detect changes.  `sources` can be of either type, simple "file newline watchers" or "differs" that run a command and check against previous output.  See the `sockets.py` source for how SC compares `netstat` output to detect new sockets being opened.  https://github.com/pirate/security-growler/blob/master/sources/sockets.py#L33

**Comment by JayBrown** [comment]
Oh, cool.

**Comment by TraderStf** [comment]
@JayBrown the sites given in my first msg are to verify, not to be used by SG.

**Comment by TraderStf** [comment]
scutil seems to have all we need.
Found all this by looking at Console, activities when switching VPN on/off.

List of VPN names (here: myVPNname) defined in Apple Network Prefs - Current Config (not all existing config in the drop down list)

<pre>
scutil --nc list
Available network connection services in the current set (*=enabled):
* (Disconnected)   A2......CC    PPP --> PPTP    "myVPName"  [PPP:PPTP]
</pre>


Status of the VPN

<pre>
scutil --nc status myVPName
Connected
Extended Status <dictionary> {
  IPv4 : <dictionary> {
    Addresses : <array> {
      0 : 10.163.......
    }
    DestAddresses : <array> {
      0 : 10.163.....
    }
    InterfaceName : ppp0
    NetworkSignature : VPN.RemoteAddress=amster.myvpnprovider.com
    OverridePrimary : 1
    Router : 10.163......
    ServerAddress : 188.172......
  }
  PPP : <dictionary> {
    CommRemoteAddress : amster.myvpnprovider.com
    ConnectTime : 21824
    IPCPCompressionVJ : 0
    LCPCompressionACField : 1
    LCPCompressionPField : 1
    LCPMRU : 1500
    LCPMTU : 1396
    Status : 8
  }
  Status : 2
}
</pre>


<pre>scutil --nc help
Valid commands for scutil --nc (VPN connections)
Usage: scutil --nc [command]

	list
		List available network connection services in the current set

	status <service>
		Indicate whether a given service is connected, as well as extended status information for the service

	show <service>
		Display configuration information for a given service

	statistics <service>
		Provide statistics on bytes, packets, and errors for a given service

	select <service>
		Make the given service active in the current set. This allows it to be started

	start <service> [--user user] [--password password] [--secret secret]
		Start a given service. Can take optional arguments for user, password, and secret

	stop <service>
		Stop a given service

	suspend <service>
		Suspend a given service (PPP, Modem on Hold)

	resume <service>
		Resume a given service (PPP, Modem on Hold)

	ondemand [-W] [hostname]
	ondemand -- --refresh
		Display VPN on-demand information

	trigger <hostname> [background] [port]
		Trigger VPN on-demand with specified hostname, and optional port and background flag

	enablevpn <service or vpn type> [path]
		Enables the given VPN application type. Takes either a service or VPN type. Pass a path to set ApplicationURL

	disablevpn <service or vpn type>
		Disables the given VPN application type. Takes either a service or VPN type

	help
		Display available commands for --nc
</pre>

**Comment by JayBrown** [comment]
The scutil command wouldn't work with my setup. (I'm using OpenVPN through utun1 with the Viscosity VPN client.)

**Comment by TraderStf** [comment]
Only if defined in Apple Network. There is also the case of a 'double' VPN, two at the same time...

**Comment by pirate** [comment]
Check out http://buttered-cat.com/products/view/MetaGrowler, it does some of the network-related things we wanted.

**Comment by pirate** [comment]
For anyone watching this, [HardwareGrowler](https://www.macupdate.com/app/mac/40750/hardwaregrowler) shows IP address and network config changes, and it works well on macOS Sierra.  I recommend downloading that and using it, as it's a great app and I'd like to have as little overlap as possible between SG and it.

![screen shot 2016-12-17 at 12 27 12 am](https://cloud.githubusercontent.com/assets/511499/21327920/638cca7e-c5ff-11e6-85ee-5ae6ea9420df.PNG)

**Comment by pirate** [comment]
Since many of the requested new alerts in this issue are covered by HardwareGrowler, I'm going to close this issue and recommend people download that app in the README.  If you guys want a specific network alert that isn't covered by HardwareGrowler, open a separate issue for it.

Here is the current state of new alert requests: 
 - new DNS change parser (tracked in https://github.com/pirate/security-growler/issues/42)
 - new public IP change (tracked in https://github.com/pirate/security-growler/issues/43)
 - new ARP resolution change (tracked in https://github.com/pirate/security-growler/issues/30)
 - √ new VPN change (covered by HardwareGrowler)
 - √ new local IP change (covered by HardwareGrowler)
 - √ new wifi/LAN connection (covered by HardwareGrowler)
 - √ new bluetooth connections (covered by HardwareGrowler)
