### ISSUE TITLE
error: BSM audit: getaddrinfo failed for...

### ISSUE THREAD

**Issue by diligiant** [pirate/security-growler#37]
I get this error a lot:

`SSH EVENT: UNKNOWN:: from:  | error: BSM audit: getaddrinfo failed for...`
`SSH EVENT:  : from:  | Could not write ident string to UNKNOWN...`

let me know if you need any trace

**Comment by pirate** [comment]
I believe this is caused by a bad network config on your LAN, and not Security Growler.  I've read of people getting this due to brute-force attacks, but it's more likely you're just getting bad traffic hitting your port 22.  Maybe due to no firewall on your router?

Either way, try adding:
`LogLevel DEBUG3`
to your `/etc/sshd_config` file.  Stop System Preferences -> Sharing -> Remote Login, then restart it.

Wait a while till you see it again, or manually trigger a failed ssh attempt, then look in `/var/log/system.log` to see what sshd entries there might be.  Post anything you find here.

Do not forget to remove the `LogLevel DEBUG3` from the `/etc/sshd_config` file when you are done testing.
Because this is not an SG issue, and is likely a system config thing, I'm closing the issue, but if you comment back here I will respond and try to help you fix it.
